version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    container_name: backend
    build: 
      context: ./backend