version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    container_name: backend
    build: 
      context: ./backend
    env_file:
      - .env

  model_classifier:
    container_name: classifier
    build:
      context: ./models/classifier

  model_wsb:
    container_name: model_wsb
    build:
      context: ./models/wallstreetbets