version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    container_name: backend
    build: 
      context: ./backend
    env_file:
      - .env

  model_classifier:
    container_name: model_classifier
    build:
      context: ./models/classifier

  model_crypto:
    container_name: model_crypto
    build: 
      context: ./models/cryptocurrency

  model_irl:
    container_name: model_irl
    build:
      context: ./models/irl

  model_wsb:
    container_name: model_wsb
    build:
      context: ./models/wallstreetbets

  model_aw:
    container_name: model_aw
    build:
      context: ./models/antiwork